[platformio]
default_envs = esp32_ek_modul
src_dir = src

[env:esp32_ek_modul]
platform = espressif32@6.5.0
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 460800

build_flags =
    -DCORE_DEBUG_LEVEL=0

